# Messages

messages:
  missing_permission:
  - "&cYou don't have &6<permission> &cpermission" # <permission> -> name of the permission
  missing_option:
  - "&cYou have to provide &6<args> &c arguments!"  # <args> -> the needed arguments
  wrong_item:
  - "&cThe &6<item> &c your holding must be &6<req_item>" # <item> -> Type of item your holding | <req_item> -> Type of required item to be hold
  error:
  - "&cFailed &4<error>" # <error> -> the error message


# Use only "/" for folders. If you want to change the bars or the Widgets or anything else. You can go to pack/assets/minecraft/textures/gui
# and change it there. The plugin will only create the folders and the .png files if they were deleted or didn't exist


# ---------------------------------------------------
#  Only tested the pack for 1.17.1 , but it should work for earlier and later minecraft versions.
# If not you can tell me to fix it on my discord server.
#  WARNING!!! The default HUD will be generated after you generate the pack.
#
#  If you provide your own .json model make sure that the texture paths are correct with the folder that you putted them.
#  The plugin won't check if the texture paths are correct if you give a custom .json model
#
# Environments, Maps and HUD doesn't support folders so "my_environments/new_sun" won't be supported!
#
# For the hats -> The textures will be stored in block textures and the models in block models
#
# Please ignore the folders "container" ; "container/creative_inventory" ; "advancements" ; "advancements/backgrounds"
# those are for generating the HUD
#
# If you need help or support. Join my discord server: https://discord.gg/tHUZtECbB5
#
# The Blocks, Armors, Environments, Maps and HUD will replace the vanilla textures. ONLY blocks can have models
#
# REMEMBER! All textures should be in lower case. This plugin won't convert it to lower case since it can brake something.
# ---------------------------------------------------
pack:
  name: "My pack"
  format: 7  # https://minecraft.fandom.com/wiki/Pack_format
  description: "Your own pack"
  blocks: # The blocks that will be used for textures ( Don't put .png or .mcmeta or .json ) Just the name
    - "block1"
    - "block2"
  block1:  # blocks don't have model data. At least for the time being, so you will replace/override already existing block with yours
    type: "dirt" # what type of block it will be. You can't have multiple textures for the same block.
    item_model: "block1"
    sides:
      south: "blockSouth"
      north: "blockNorth"
      east: "blockEast"
      west: "blockWest"
      up: "blockUp"
      down: "blockDown"
      particle: "blockParticle" # the textures for the particle of the block
    animation:
      enable: true  # if you have animations.
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  block2:  # You can add hats
    type: "stone_slab"  # use _ instead of space
    item_model: "block2"
    sides:
      south: "blockSouth"
      north: "blockNorth"
      east: "blockEast"
      west: "blockWest"
      up: "blockUp"
      down: "blockDown"
      particle: "blockParticle" # the textures for the particle of the block
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  items:
    - "new_items/item1"  # the texture can be also in a folder. NO system paths. Just paths in folder items/
    - "item2"
  new_item/item1:
    type: "stone_sword" # if the item is invalid it will be replaced with stone_sword for items and dirt for blocks.
    item_model: "new_item/item1" # if you have your own custom item model for this item then you can change the path to it.  NO system paths. Just paths in folder items/
    model_data: 1 # you can set multiple textures for one item
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10  # 10 seconds before switching to the other frame. The frames are vertical. The top frame is the first and the bottom frame is the last.
      2:
        time: 5  # 1 and 2  are not INDEX they are like: 1st frame, 2nd frame and so on.
  item2:
    type: "axe"  # use for multiple states of fishing rod or bows (those are pure hell to made them work)
    item_model: "item2"
    model_data: 1  # you can have all your overrides/textures to be the same number as long as they are different items.
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  emojis: # You can use emojis for custom: GUI | Emoji | Ranks | Tags
    - "emoji1"
    - "emoji2"
  emoji1: # to test it use /tellraw @a {"text": "\uE001"}
    chars:
    - "\uE001" # This is the letter/character that the pack will replace with a png. It is recommended to use invalid chars like that one.
    type: "bitmap"
    height: 10
    ascent: 9
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  emoji2:
    chars:  # assets/minecraft/font/default.json  -> look for chars and change it there. If you see "?" in chars just change it
    - "\uE002" # only one emoji per char. You can add rank tags with emojis. If the emoji doesn't work then you can go to
    type: "bitmap" # the type of the .png file
    height: 10
    ascent: 9
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  hats:
    - "hat1"
    - "hat2"
  hat1:
    remove_pumpkin: true  # if you DON'T want to see the blur pumpkin texture when you put your hat on.
    item_model: "hat1" # the model for the hat .json format.
    hat_pumpkin_texture: "hat_pumpkin" # If you want to change the overlay on the player's screen when a player puts on the hat.
    model_data: 1 # the model data for the hat
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  hat2:
    remove_pumpkin: true
    item_model: "hat2"
    hat_pumpkin_model: "hat_pumpkin"
    model_data: 1
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  armors:
    - "armor1"
    - "armor2"
  armor1:
    type: "iron_layer_1"
    model_data: 1
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  armor2:
    type: "diamond_layer_2"
    model_data: 1
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  environments: # you can only set: sun ; snow ; rain ; moon_phases ; end_sky ; clouds
    - "sun"
    - "snow"
  sun:
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  snow:
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  maps: # you can only set: map_icons ; map_background ; map_background_checkerboard
    - "map_icons"
    - "map_background"
  map_icons:
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  map_background:
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5

