# Messages

messages:
  missing_permission:
  - "&cYou don't have &6<permission> &cpermission" # <permission> -> name of the permission
  missing_option:
  - "&cYou have to provide &6<args> &c arguments!"  # <args> -> the needed arguments
  wrong_item:
  - "&cThe &6<item> &c your holding must be &6<req_item>" # <item> -> Type of item your holding | <req_item> -> Type of required item to be hold
  error:
  - "&cFailed &4<error>" # <error> -> the error message



pack:
  format: 7  # https://minecraft.fandom.com/wiki/Pack_format
  description: "Your own pack"
  blocks: # The blocks that will be used for textures ( Don't put .png or .mcmeta or .json ) Just the name
    - "block1"
    - "block2"
  block1:  # blocks don't have model data. At least for the time being, so you will replace/override already existing block with yours
    type: "dirt" # what type of block it will be
    animation:
      enable: true  # if you have animations.
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  block2:  # You can add hats
    type: "stone_slab"  # use _ instead of space
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  items:
    - "new_items/item1"  # the texture can be also in a folder
    - "item2"
  item1:
    type: "stone_sword" # if the item is invalid it will be replaced with stone_sword for items and dirt for blocks.
    model_data: 1 # you can set multiple textures for one item
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10  # 10 seconds before switching to the other frame. The frames are vertical. The top frame is the first and the bottom frame is the last.
      2:
        time: 5  # 1 and 2  are not INDEX they are like: 1st frame, 2nd frame and so on.
  item2:
    type: "axe"  # use for multiple states of fishing rod or bows (those are pure hell to made them work)
    model_data: 1  # you can have all your overrides/textures to be the same number as long as they are different items.
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  emojis:
    - "emoji1"
    - "emoji2"
  emoji1: # to test it use /tellraw @a {"text": "\uE001"}
    chars: "\uE001" # This is the letter/character that the pack will replace with a png. It is recommended to use invalid chars like that one.
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  emoji2:
    chars: "\uE002" # only one emoji per char. You can add rank tags with emojis.
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  hats:
    - "hat1"
    - "hat2"
  hat1:
    remove_pumpkin: true
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
  hat2:
    remove_pumpkin: true
    animation:
      enable: true
      amount_of_frames: 2
      1:
        time: 10
      2:
        time: 5
